import type { Mascota } from './MascotasPage.types';

// Datos simulados. Cuando conectemos la API, este archivo se elimina.
const mascotasMock: Mascota[] = [
  {
    id: 1,
    nombre: 'Luna',
    especie: 'Perro',
    raza: 'Golden Retriever',
    sexo: 'H',
    fecha_nacimiento: '2022-03-15',
    peso_kg: 25.5,
    activo: true,
    propietario_id: 1,
    propietario_nombre: 'Carlos',
    propietario_apellidos: 'Ramírez',
    telefono: '555-0123',
  },
  {
    id: 2,
    nombre: 'Michi',
    especie: 'Gato',
    raza: 'Siamés',
    sexo: 'M',
    fecha_nacimiento: '2023-01-20',
    peso_kg: 4.2,
    activo: true,
    propietario_id: 2,
    propietario_nombre: 'Ana',
    propietario_apellidos: 'López',
    telefono: '555-0456',
  },
  {
    id: 3,
    nombre: 'Rocky',
    especie: 'Perro',
    raza: 'Bulldog Francés',
    sexo: 'M',
    fecha_nacimiento: '2021-08-05',
    peso_kg: 12.0,
    activo: true,
    propietario_id: 1,
    propietario_nombre: 'Carlos',
    propietario_apellidos: 'Ramírez',
    telefono: '555-0123',
  },
  {
    id: 4,
    nombre: 'Nube',
    especie: 'Gato',
    raza: 'Persa',
    sexo: 'H',
    fecha_nacimiento: '2023-07-12',
    peso_kg: 3.8,
    activo: true,
    propietario_id: 3,
    propietario_nombre: 'María',
    propietario_apellidos: 'Torres',
    telefono: '555-0789',
  },
];

export default mascotasMock;
